name = "Jukebox"
uuid = "aba77599-5ab6-407a-a2ba-a899503035b6"
version = "0.1.0"
authors = ["Fran Barton <fbarton@alwaysdata.net>"]

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
PkgTemplates = "0.7.56"
julia = "1.6"
